import './globals.css'
import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import Header from './Essentials/Header'
import Footer from './Essentials/Footer'

const inter = Sora({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Landing Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}><div className=''><Header/><div>{children}</div><Footer/></div></body>
    </html>
  )
}
